### PR TITLE
refactor manager

### PR DESCRIPTION
**Pull request by mfrederickson**
@markmeyerphoto I simplified the loaddata.js by using the knex.bulkInsert like we discussed, but then the tests failed because the implicit transaction the bulkInsert was using was not committing before the row counts were being checked.  So I ended up refactoring the manager a little as well to support explicitly committing the transaction for that.  One thing you'll want to look at is that it is no longer using a (cached)  KNEX variable-- it's setting it each time.

### CODE REVIEW

**Comment by mfrederickson** [comment]
@markmeyerphoto also refactored db.js to include the encrypt/decrypt functions so it's all in one place.

**Comment by markmeyerphoto** [comment]
I think these are great changes. When you looked at this did you get any sense of why they where caching the knex connection manually rather than letting require() do it? The docs say the init should only run once in an app's lifecycle, but it seems like it still only runs once if we call knex() in manager.js and return the value.

**Comment by mfrederickson** [comment]
No, I have no idea.  I thought maybe I was missing something...

**Comment by markmeyerphoto** [comment]
That's encouraging. I thought the same thing.

**Comment by mfrederickson** [comment]
If you see this in the console:
```
Error:  undefined
TypeError: res.status is not a function
```
this PR fixes it. (web.js, putting the next arg back in place)

**Comment by markmeyerphoto** [comment]
Yeah, I'm getting that error. Would be nice to get this into the main branch.

**Pull request merged**
