### PR TITLE
style and script test page closer to messaging on phone

### PR DESCRIPTION
**Pull request by mfrederickson**
image

### CODE REVIEW

**Comment by mfrederickson** [comment]
@tescher this is ready to be merged at your convenience (I am unable to assign a reviewer)

**Comment by mark-meyer** [comment]
Hey @mfrederickson I think this it really cool and we were recently talking about merging this, but it was behind the master branch far enough that I wasn't sure how to bring it up without making a whole new branch. Do you think it's as easy as you pulling the current master into it and pushing the PR again?

**Comment by mfrederickson** [comment]
Yeah, I'll do that.  Sorry, I just figured I'd close it out since it didn't
look like there was going to be any action on it.

**Comment by mfrederickson** [comment]
I'll reopen this, but I still need to do some testing on it-- I was unable to load some data as explained in the readme-- something about the hearings relation missing...

**Comment by mfrederickson** [comment]
Seems to work just fine. It's ready to merge.

**Comment by brendanbabb** [comment]
Looks good

**Pull request merged**
